# Site settings
title: RN Mobility
description: Learn the basics of registered nurse license endorsement, renewal, and continuing education in the USA. Keep your nursing credentials up to date.
url: https://acls.net/rn-mobility/
permalink: "/:path"
google_analytics_id: G-RJB2BBT9M7
lang: en-US

exclude:
  - README.md
  - vendor
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - BACKUPS

destination: build
source: source
