# Site settings
title: RN Mobility
url: https://rnmobility.com/
#permalink: pretty
google_analytics_id: G-RJB2BBT9M7

exclude:
  - README.md
  - vendor
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - BACKUPS
